name = "MTIWrapper"
uuid = "0746e27f-2406-533c-aa7f-32ff14289989"
author = ["Brown Center for Biomedical Informatics"]
version = "0.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"

[targets]
test = ["Test", "CSV"]